
@startuml CharacterRelation

object 研究者 {
  要検討
  --
  魔法使いと役割被りを避けたい
}

object 魔法使い {
  地上
  対地, 対空(弱)
  遠隔 範囲攻撃
  --
  + 範囲攻撃で群れを一掃
  - 攻撃詠唱が遅い, 運用は前衛が必須
}

object ハンマー使い {
  地上
  対地
  近接 単体攻撃
  --
  + 強力な単体攻撃で大型の敵を粉砕
  - 攻撃間隔は長め, 小型の群れには弱い
}

object 剣士 {
  地上
  対地
  近接 単体攻撃
  --
  スタンダードなユニット
  + コスパよし 何に対しても程々に有効
}

object 槍使い {
  地上
  対地
  中距離 単体攻撃
  --
  + 中射程の素早い攻撃で近接を完封
  - 打たれ弱い, 遠距離攻撃で死ぬ
}

object 弓使い {
  地上
  対地, 対空
  遠隔 単体攻撃
  --
  + 遠距離攻撃で援護
  + 空中ユニットへのほぼ唯一の回答
  - 低い基礎性能
}

object 空中ユニット<<未定>> {
  空中, 対地
  近接 単体攻撃
  --
  + 対空能力を持たないユニットを一方的に攻撃
  - 打たれ弱い, 対処されるとすぐ死ぬ
}

object 群れユニット<<未定>> {
  地上, 対地
  近接 単体攻撃
  --
  + 一度に複数体召喚される
  + 単体攻撃での対処は時間が掛かる
  - 範囲攻撃に弱い
  
}

object 大型ユニット<<未定>> {
  地上, 対地
  近接 高威力単体攻撃
  --
  ゴーレムみたいなやつ。
  + 硬い,のけぞらない
  - 高コスト
  - 低移動速度
}

object 盾兵<<未定>> {
  地上
  --
  + 攻撃せず盾を構える
  + 遠距離攻撃を無効化する
  - 攻撃しないので単体では無意味
}


槍使い --> 剣士

空中ユニット --> 槍使い
空中ユニット --> 剣士
空中ユニット --> ハンマー使い

剣士 --> 弓使い
剣士 --> 魔法使い

弓使い --> 空中ユニット

魔法使い --> 群れユニット

群れユニット --> ハンマー使い
群れユニット --> 大型ユニット

大型ユニット --> 槍使い
大型ユニット --> 剣士
大型ユニット --> ハンマー使い

盾兵 --> 弓使い
盾兵 --> 魔法使い


@enduml